### ISSUE TITLE
Add details of the GNU GPL license.

### ISSUE THREAD

**Issue by camfindlay** [hpmewes/silverstripe-siteconfigextension#2]
Hey, will be good to ensure you include the details of the GPL if you intend to release this under that copyleft license. Most SilverStripe modules are under the BSD or MIT. This could lead to some incompatibilities between the use of our module and other modules etc. Other options might be to consider using BSD or dual licensing perhaps.

**Comment by hpmewes** [comment]
Hello,
i will have a look between the differences about that. i write back if i have a dessicion.

**Comment by hpmewes** [comment]
Hello,
i've changed to BSD License.

**Comment by camfindlay** [comment]
@hpmewes nice one!
